### ISSUE TITLE
Make install_github return names of installed package

### ISSUE THREAD

**Issue by jeroen** [r-pkgs/remotes#63] opened 2017-05-01 09:48 UTC
Sometimes the name of the github repository does not match the name of the package name in it.

A super useful feature would be if `install_github()` returns the full name (or path) of the installed package, so that I know what has been installed when using  `install_github()` for programming.

**Comment by gaborcsardi** [comment] 2017-05-01 09:49
Duplicate of #55.

**Closed by gaborcsardi** 2017-05-01 09:49 UTC
